In [2]:
# to import the module
import pandas as pd

In [32]:
# to import as csv & separated
hagebau = pd.read_csv("C:/Users/yj_pc/Desktop/berlin/htw berlin/MPMD_Dateien/1.2 Fdns Data Analytics & Stats Prog/001_Data_CONFIDENTIAL/records_116007_from_2017-03-01_to_2017-03-31.csv", sep=',')
hagebau

,mainBusinessType,location,datetime,cashRegisterNumber,checkoutReceiptNumber,receiptNumber,loyaltyId,productEan,productId,commodityGroup,productGroup,amount,grossPrice
0,30,116007,2017-03-25T07:07:00.000Z,546,2,76201999,NaN,4.333990e+12,182021,9855,908,2.0,1.98
1,30,116007,2017-03-25T07:10:00.000Z,546,3,76202000,8.011080e+11,4.046810e+12,45380327,9853,904,1.0,2.09
2,30,116007,2017-03-25T07:10:00.000Z,546,3,76202000,8.011080e+11,4.046810e+12,45380362,9853,904,1.0,2.32
3,30,116007,2017-03-25T07:10:00.000Z,546,3,76202000,8.011080e+11,4.046810e+12,682540,9853,904,1.0,3.10
4,30,116007,2017-03-25T07:10:00.000Z,546,3,76202000,8.011080e+11,4.046810e+12,965278,9865,903,1.0,4.42
5,30,116007,2017-03-25T07:10:00.000Z,546,3,76202000,8.011080e+11,4.006560e+12,965506,9847,891,1.0,8.53
6,30,116007,2017-03-25T07:11:00.000Z,546,4,76202001,NaN,4.000730e+12,840310,9841,885,1.0,44.95
7,30,116007,2017-03-25T07:13:00.000Z,546,5,76202002,8.011060e+11,4.046810e+12,492462,9274,1592,1.0,3.39
8,30,116007,2017-03-25T07:13:00.000Z,546,5,76202002,8.011060e+11,4.004720e+12,246430,9721,1977,1.0,2.22
9,30,116007,2017-03-25T07:13:00.000Z,546,5,76202002,8.011060e+11,4.046810e+12,682200,9853,907,1.0,3.39
10,30,116007,2017-03-25T07:14:00.000Z,546,6,76202003,8.011030e+11,4.014440e+11,387340,9608,514,1.0,12.60
11,30,116007,2017-03-25T07:21:00.000Z,546,7,76202004,NaN,4.046810e+12,45342691,9152,39,1.0,2.49
12,30,116007,2017-03-25T07:21:00.000Z,546,7,76202004,NaN,4.046810e+12,45342706,9152,39,1.0,8.49
13,30,116007,2017-03-25T07:21:00.000Z,546,7,76202004,NaN,4.046810e+12,45342773,9152,39,1.0,7.99
14,30,116007,2017-03-25T07:21:00.000Z,546,7,76202004,NaN,4.046810e+12,45337794,9152,39,1.0,17.99
15,30,116007,2017-03-25T07:21:00.000Z,546,7,76202004,NaN,4.078555e+07,45331913,9152,38,5.0,29.95
16,30,116007,2017-03-25T07:22:00.000Z,546,8,76202489,8.011030e+11,4.005010e+12,310402,9311,1737,3.0,7.92
17,30,116007,2017-03-25T07:22:00.000Z,546,8,76202489,8.011030e+11,4.005010e+12,310030,9311,1737,5.0,4.75
18,30,116007,2017-03-25T07:31:00.000Z,546,9,76202490,8.011020e+11,4.008060e+12,331302,9785,737,1.0,9.21
19,30,116007,2017-03-25T07:31:00.000Z,546,9,76202490,8.011020e+11,4.006680e+12,187040,9372,1798,4.0,6.56
20,30,116007,2017-03-25T07:31:00.000Z,546,9,76202490,8.011020e+11,4.006680e+12,174912,9372,1798,2.0,5.80
21,30,116007,2017-03-25T07:34:00.000Z,546,10,76202491,NaN,4.017080e+12,45355808,9672,803,1.0,12.99
22,30,116007,2017-03-25T07:34:00.000Z,546,10,76202491,NaN,4.017080e+12,905202,9671,797,1.0,19.99
23,30,116007,2017-03-25T07:36:00.000Z,546,11,76202492,NaN,4.032530e+12,294351,9701,696,1.0,3.49
24,30,116007,2017-03-25T07:36:00.000Z,546,11,76202492,NaN,4.042450e+12,103679,9865,903,1.0,4.99
25,30,116007,2017-03-25T07:36:00.000Z,546,11,76202492,NaN,4.006560e+12,832319,9832,881,1.0,7.99
26,30,116007,2017-03-25T07:36:00.000Z,546,11,76202492,NaN,4.006210e+12,731910,9703,1903,1.0,2.99
27,30,116007,2017-03-25T07:37:00.000Z,546,12,76202493,NaN,4.004720e+12,494423,9721,2021,1.0,1.49
28,30,116007,2017-03-25T07:47:00.000Z,546,13,76202494,8.011080e+11,4.046810e+12,45320478,9215,1615,3.0,52.35
29,30,116007,2017-03-25T07:47:00.000Z,546,13,76202494,8.011080e+11,4.015000e+12,860480,9861,893,1.0,4.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...
27451,30,116007,2017-03-01T00:00:00.000Z,99999,99999,69845777,NaN,1.000000e+13,909165,9165,10165,1.0,89.00
27452,30,116007,2017-03-01T00:00:00.000Z,99999,99999,69845777,NaN,1.000000e+13,909162,9162,10162,1.0,259.00
27453,30,116007,2017-03-01T00:00:00.000Z,99999,99999,69845777,NaN,1.000000e+13,909162,9162,10162,1.0,199.00
27454,30,116007,2017-03-01T00:00:00.000Z,99999,99999,69845778,NaN,5.411180e+12,592521,9274,1592,-1.0,-8.99
27455,30,116007,2017-03-01T00:00:00.000Z,99999,99999,69845778,NaN,5.411180e+12,592522,9274,1592,-1.0,-7.49
27456,30,116007,2017-03-01T00:00:00.000Z,99999,99999,69845845,8.011030e+11,4.003790e+12,802842,9803,590,-1.0,-19.39
27457,30,116007,2017-03-01T00:00:00.000Z,99999,99999,69845852,NaN,4.002400e+12,45363154,9812,922,-1.0,-9.99
27458,30,116007,2017-03-01T00:00:00.000Z,99999,99999,69845853,NaN,4.008060e+12,45421801,9788,1961,-1.0,-5.81
27459,30,116007,2017-03-01T00:00:00.000Z,99999,99999,69845853,NaN,4.008840e+12,200351,9563,3147,-1.0,-22.26
27460,30,116007,2017-03-15T00:00:00.000Z,99999,99999,73257356,NaN,3.165140e+12,654455,9606,474,-1.0,-7.50
27461,30,116007,2017-03-15T00:00:00.000Z,99999,99999,73257356,NaN,4.038370e+12,45421051,9606,474,-1.0,-72.70
27462,30,116007,2017-03-15T00:00:00.000Z,99999,99999,73257357,NaN,4.007840e+12,913295,9911,949,-1.0,-19.39
27463,30,116007,2017-03-15T00:00:00.000Z,99999,99999,73257358,8.011030e+11,5.702160e+12,985314,9843,887,-2.0,-81.38
27464,30,116007,2017-03-15T00:00:00.000Z,99999,99999,73257359,8.011030e+11,4.008220e+12,910114,9911,949,-1.0,-4.66
27465,30,116007,2017-03-15T00:00:00.000Z,99999,99999,73257360,NaN,4.019240e+12,909782,9782,10782,-1.0,-4.94
27466,30,116007,2017-03-15T00:00:00.000Z,99999,99999,73257361,NaN,4.046810e+12,45423757,9141,420,-1.0,-134.83
27467,30,116007,2017-03-15T00:00:00.000Z,99999,99999,73257829,NaN,3.165140e+12,493863,9764,1032,-1.0,-46.51
27468,30,116007,2017-03-15T00:00:00.000Z,99999,99999,73257832,8.011080e+11,4.006560e+12,472290,9825,874,-2.0,-44.54
27469,30,116007,2017-03-15T00:00:00.000Z,99999,99999,73257832,8.011080e+11,4.006560e+12,291590,9825,874,-1.0,-19.39
27470,30,116007,2017-03-15T00:00:00.000Z,99999,99999,73257833,NaN,8.838166e+10,45423935,9762,812,-1.0,-251.23
27471,30,116007,2017-03-15T00:00:00.000Z,99999,99999,73257834,NaN,4.006940e+12,634714,9803,590,-1.0,-9.69
27472,30,116007,2017-03-15T00:00:00.000Z,99999,99999,73257835,NaN,1.000000e+13,909743,9743,10743,1.0,6.47
27473,30,116007,2017-03-15T00:00:00.000Z,99999,99999,73257835,NaN,1.000000e+13,909743,9743,10743,1.0,32.39
27474,30,116007,2017-03-15T00:00:00.000Z,99999,99999,73257836,NaN,4.027410e+12,45167308,9501,1042,-1.0,-17.80
27475,30,116007,2017-03-15T00:00:00.000Z,99999,99999,73257836,NaN,8.029430e+12,45281400,9502,1053,-1.0,-28.23
27476,30,116007,2017-03-15T00:00:00.000Z,99999,99999,73257837,8.011070e+11,4.035300e+12,218428,9551,1234,-2.0,-11.04
27477,30,116007,2017-03-15T00:00:00.000Z,99999,99999,73257838,8.011030e+11,4.002350e+12,165406,9756,758,-1.0,-29.05
27478,30,116007,2017-03-15T00:00:00.000Z,99999,99999,73258323,NaN,4.026700e+12,45012539,9602,520,-1.0,-10.50
27479,30,116007,2017-03-15T00:00:00.000Z,99999,99999,73258324,NaN,4.035300e+12,117506,9773,832,-1.0,-11.99
27480,30,116007,2017-03-15T00:00:00.000Z,99999,99999,73258325,NaN,4.002710e+12,206148,9938,982,-2.0,-42.60

In [1]:
# filtering
filt=hagebau.dropna()

filt = filt[filt.grossPrice < 0]
filt

filt.count()

# to export csv
filt.to_csv("C:/Users/yj_pc/Desktop/testexport.csv")

NameError: name 'hagebau' is not defined

In [16]:
# to import as csv
hagebau = pd.read_csv("C:/Users/yj_pc/Desktop/berlin/htw berlin/MPMD_Dateien/1.2 Fdns Data Analytics & Stats Prog/001_Data_CONFIDENTIAL/records_116007_from_2017-03-01_to_2017-03-31.csv", sep = ';')

# to drop records with no values
hagebau.dropna()
hagebau.count()

# to get data type 
type(hagebau)

# to drop records with no values IN A PARTICULAR COLUMN
filt = hagebau.dropna(subset=['loyaltyId'])

KeyError: ['loyaltyId']

In [11]:
dict = {"ruthra":1,"haris":2}

# TO PRINT OUT INDICES
for asd in dict:
    print(asd)

ruthra
haris

In [12]:
dict = {"ruthra":1,"haris":2}

# TO PRINT OUT VALUES
for asd in dict.values():
    print(asd)

1
2